// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AlertStack: typeof import("./src/components/AlertStack.vue")["default"];
    BatchJsonCreateDialog: typeof import("./src/components/Dialogs/BatchJsonCreateDialog.vue")["default"];
    CalendarView: typeof import("./src/components/PrintScheduling/CalendarView.vue")["default"];
    CreatePrinterDialog: typeof import("./src/components/Dialogs/CreatePrinterDialog.vue")["default"];
    CreatePrinterGroupDialog: typeof import("./src/components/Dialogs/CreatePrinterGroupDialog.vue")["default"];
    FileControlList: typeof import("./src/components/PrinterList/FileControlList.vue")["default"];
    FileExplorerSideNav: typeof import("./src/components/SideNavs/FileExplorerSideNav.vue")["default"];
    FormText: typeof import("./src/components/Forms/FormText.vue")["default"];
    FormTextArea: typeof import("./src/components/Forms/FormTextArea.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    Login: typeof import("./src/components/Login.vue")["default"];
    NavigationDrawer: typeof import("./src/components/NavigationDrawer.vue")["default"];
    PrinterChecksPanel: typeof import("./src/components/Dialogs/PrinterChecksPanel.vue")["default"];
    PrinterConnectionAction: typeof import("./src/components/Actions/PrinterConnectionAction.vue")["default"];
    PrinterCrudForm: typeof import("./src/components/Forms/PrinterCrudForm.vue")["default"];
    PrinterDeleteAction: typeof import("./src/components/Actions/PrinterDeleteAction.vue")["default"];
    PrinterDetails: typeof import("./src/components/PrinterList/PrinterDetails.vue")["default"];
    PrinterGrid: typeof import("./src/components/PrinterGrid/PrinterGrid.vue")["default"];
    PrinterGridTile: typeof import("./src/components/PrinterGrid/PrinterGridTile.vue")["default"];
    PrinterGroupCrudForm: typeof import("./src/components/Forms/PrinterGroupCrudForm.vue")["default"];
    PrinterSettingsAction: typeof import("./src/components/Actions/PrinterSettingsAction.vue")["default"];
    PrinterUrlAction: typeof import("./src/components/Actions/PrinterUrlAction.vue")["default"];
    PrintJobsMenu: typeof import("./src/components/PrintJobsMenu.vue")["default"];
    RefreshFilesAction: typeof import("./src/components/Actions/RefreshFilesAction.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"];
    TopBar: typeof import("./src/components/TopBar.vue")["default"];
    UpdatePrinterDialog: typeof import("./src/components/Dialogs/UpdatePrinterDialog.vue")["default"];
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"];
  }
}

export {};
